{% set name = "gto" %}
{% set version = "1.7.1" %}
package:
  name: {{ name|lower }}
  version: {{ version }}
source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gto-{{ version }}.tar.gz
  sha256: 24100e735195c0d54539401f42804fc9042998276cdc4233f49f153fd38a7d75
build:
  entry_points:
    - gto = gto.cli:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
requirements:
  host:
    - python >=3.9
    - setuptools >=48
    - setuptools-scm >=6.3.1
    - setuptools_scm_git_archive ==1.1
    - fastentrypoints >=0.12
    - pip
  run:
    - python >=3.9
    - scmrepo >=3,<4
    - typer >=0.4.1
    - rich
    - pydantic >=1.9.0,<3,!=2.0.0
    - ruamel.yaml
    - semver >=2.13.0
    - entrypoints
    - tabulate >=0.8.10
    - funcy
test:
  imports:
    - gto
  commands:
    - pip check
    - gto --help
  requires:
    - pip
about:
  summary: Version and deploy your models following GitOps principles
  license: Apache-2.0
  license_file: LICENSE
  home: https://github.com/iterative/gto
  dev_url: https://github.com/iterative/gto
  doc_url: https://dvc.org/doc/gto
  doc_source_url: https://github.com/iterative/dvc.org/tree/main/content/docs/gto
extra:
  recipe-maintainers:
    - aguschin
    - shcheklein
    - pmrowla
    - bgalvao
    - janjagusch
    - efiop
    - skshetry
