schema_version: 1

context:
  name: gto
  version: 1.7.2

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/gto-${{ version }}.tar.gz
  sha256: 98994f43d02ef6d4e77c4087b1c0c70a038e4a753a5583c23116246d33b89742

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - gto = gto.cli:app

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=48
    - setuptools-scm >=6.3.1
    - setuptools_scm_git_archive ==1.1
    - fastentrypoints >=0.12
    - pip
  run:
    - python >=${{ python_min }}
    - scmrepo >=3,<4
    - typer >=0.4.1
    - rich
    - pydantic >=1.9.0,<3,!=2.0.0
    - ruamel.yaml
    - semver >=2.13.0
    - entrypoints
    - tabulate >=0.8.10
    - funcy

tests:
  - python:
      imports:
        - gto
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check
      - gto --help

about:
  summary: Version and deploy your models following GitOps principles
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/iterative/gto
  repository: https://github.com/iterative/gto
  documentation: https://dvc.org/doc/gto

extra:
  recipe-maintainers:
    - aguschin
    - shcheklein
    - pmrowla
    - bgalvao
    - janjagusch
    - efiop
    - skshetry
